version: '3.7'  # 파일 규격 버전
services:       # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  prometheus:
    image: prom/prometheus:latest
    user: "0:0"
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - 9090:9090 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=6h'             # Prometheus는 최근 6시간만 유지
      - '--storage.tsdb.min-block-duration=2h'         # block 단위 2시간
      - '--storage.tsdb.max-block-duration=2h'
      - '--external-label=cluster=prod'         # Thanos 필수
      - '--external-label=replica=vm1'          # 고유 레이블
      #- '--external-label=cluster=prod'     # 클러스터 식별 레이블

    restart: always
    networks:
      - promnet
  
  thanos-sidecar:
    image: thanosio/thanos:v0.37.2
    command:
      - sidecar
      - --tsdb.path=/prometheus
      - --http-address=0.0.0.0:10902
      - --grpc-address=0.0.0.0:10901
      - --prometheus.url=http://prometheus:9090
      - --objstore.config-file=/etc/thanos/bucket.yaml
    volumes:
      - ./thanos/bucket.yaml:/etc/thanos/bucket.yaml  # MinIO connection
    ports:
      - "10901:10901"  
    networks:
      - promnet
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0:0"
    ports:
      - 3000:3000 # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    volumes:
      - ./grafana/volume:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards    # 대시보드 지정
      - ./grafana/provisioning:/etc/grafana/provisioning    # 지정한 대시보드 불러오기 및 프로메테우스 uid 고정(충돌방지)
    environment:  # ✅ 환경 변수 설정
    - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    networks:
      - promnet

  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - promnet

networks:
  promnet:
    driver: bridge
