events {
    worker_connections 1024;  # 기본값으로 worker_processes에 할당할 최대 연결 수
}

http {
    # HTTP 관련 설정들
    include       mime.types;
    default_type  application/octet-stream;

    # 로그 포맷을 JSON 형식으로 설정
    log_format json '{'
                      '"@timestamp": "$time_iso8601",'
                      '"host": "$remote_addr",'
                      '"request": "$request",'
                      '"status": "$status",'
                      '"body_bytes_sent": "$body_bytes_sent",'
                      '"request_time": "$request_time",'
                      '"upstream_response_time": "$upstream_response_time",'
                      '"http_user_agent": "$http_user_agent",'
                      '"remote_user": "$remote_user",'
                      '"request_method": "$request_method",'
                      '"uri": "$uri",'
                      '"referer": "$http_referer",'
                      '"remote_port": "$remote_port",'
                      '"server_name": "$server_name",'
                      '"server_addr": "$server_addr"'
                    '}';

    # 로그를 JSON 형식으로 저장
    access_log /var/log/nginx/access.log json;
    error_log /var/log/nginx/error.log warn;

    
    server {
        listen 80;
        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
}
