input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["logs"]
    group_id => "logstash-group"
    consumer_threads => 1
    decorate_events => true
    auto_offset_reset => "earliest"
  }
}

filter {
  if [message] =~ "^{.*}$" {
    json {
      source => "message"
    }
  } else {
    mutate {
      add_field => { "raw_message" => "%{message}" }
    }
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
